# Generated by Django 3.0.1 on 2020-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200113_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
